import Cocoa
import SafariServices

/// Replace the handler generated by `safari-web-extension-packager` with this file.
/// Safari sends runtime.sendNativeMessage payloads to this containing-app extension.
/// The bridge forwards one JSON message to OriginKeep's stable per-user native host.
final class SafariWebExtensionHandler: NSObject, NSExtensionRequestHandling {
    func beginRequest(with context: NSExtensionContext) {
        let responseItem = NSExtensionItem()
        let requestItem = context.inputItems.first as? NSExtensionItem
        let message = requestItem?.userInfo?[SFExtensionMessageKey]

        do {
            guard let message else {
                throw BridgeError.invalidMessage
            }
            let response = try forwardToOriginKeep(message)
            responseItem.userInfo = [SFExtensionMessageKey: response]
        } catch {
            responseItem.userInfo = [
                SFExtensionMessageKey: [
                    "ok": false,
                    "error": "OriginKeep Safari bridge: \(error.localizedDescription)"
                ]
            ]
        }

        context.completeRequest(returningItems: [responseItem], completionHandler: nil)
    }

    private func forwardToOriginKeep(_ message: Any) throws -> Any {
        let home = FileManager.default.homeDirectoryForCurrentUser
        let hostURL = home
            .appendingPathComponent("Library/Application Support/OriginKeep/bin", isDirectory: true)
            .appendingPathComponent("originkeep-native-host", isDirectory: false)

        guard FileManager.default.isExecutableFile(atPath: hostURL.path) else {
            throw BridgeError.hostMissing(hostURL.path)
        }

        let json = try JSONSerialization.data(withJSONObject: message)
        guard json.count <= 1024 * 1024 else {
            throw BridgeError.messageTooLarge
        }

        var littleEndianLength = UInt32(json.count).littleEndian
        var framed = Data(bytes: &littleEndianLength, count: MemoryLayout<UInt32>.size)
        framed.append(json)

        let process = Process()
        let input = Pipe()
        let output = Pipe()
        let errors = Pipe()
        process.executableURL = hostURL
        process.standardInput = input
        process.standardOutput = output
        process.standardError = errors
        try process.run()
        try input.fileHandleForWriting.write(contentsOf: framed)
        try input.fileHandleForWriting.close()

        guard let lengthData = try output.fileHandleForReading.read(upToCount: 4),
              lengthData.count == 4 else {
            process.terminate()
            throw BridgeError.invalidResponse
        }
        let responseLength = lengthData.withUnsafeBytes { rawBuffer -> UInt32 in
            rawBuffer.load(as: UInt32.self).littleEndian
        }
        guard responseLength <= 1024 * 1024,
              let responseData = try output.fileHandleForReading.read(upToCount: Int(responseLength)),
              responseData.count == Int(responseLength) else {
            process.terminate()
            throw BridgeError.invalidResponse
        }
        process.waitUntilExit()
        return try JSONSerialization.jsonObject(with: responseData)
    }
}

private enum BridgeError: LocalizedError {
    case invalidMessage
    case messageTooLarge
    case invalidResponse
    case hostMissing(String)

    var errorDescription: String? {
        switch self {
        case .invalidMessage:
            return "Safari did not provide a native message payload."
        case .messageTooLarge:
            return "The message exceeded OriginKeep's 1 MiB native-message limit."
        case .invalidResponse:
            return "The OriginKeep native host returned an invalid response."
        case .hostMissing(let path):
            return "OriginKeep native host is not installed at \(path). Open OriginKeep and run Browser integration first."
        }
    }
}
